const edgeCaseComments = [
    'bad',
    'not good',
    'not up to the mark',
    'not upto mark',
    'not up to mark',
    'not upto the mark',
    'not great',
    'not that great',
    'subpar',
    'inferior quality',
    'poor performance',
    'below expectations',
    'disappointing',
    'lacking',
    'unsatisfactory',
    'substandard',
    'inferior',
    'unimpressive',
    'mediocre',
    'awful',
    'underwhelming',
    'not impressive',
    'could be better',
    'room for improvement',
    'needs improvement',
    'falls short',
    'not satisfactory',
    'not meeting expectations',
    'not meeting standards',
    'not meeting requirements',
  ];
   export default edgeCaseComments
